name: analysis_server_lib
description: A library to access Dart's analysis server API.

version: 0.2.0
homepage: https://github.com/devoncarew/analysis_server_lib

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  html: ^0.15.0
  pedantic: ^1.11.0
  test: ^1.16.5
