name: analysis_server_lib
description: A library to access Dart's analysis server API.

version: 0.1.4
author: Devon Carew <devoncarew@google.com>
homepage: https://github.com/devoncarew/analysis_server_lib

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  logging: ^0.11.0
  path: ^1.0.0

dev_dependencies:
  html: ^0.13.0
  test: ^0.12.0
